Debug results

diff --git a/.gitea/workflows/dev.yaml b/.gitea/workflows/dev.yaml
--- a/.gitea/workflows/dev.yaml
+++ b/.gitea/workflows/dev.yaml
@@ -91,6 +91,12 @@ jobs:
       - release
       - test
     steps:
+      - name: debugging
+        run: |
+          echo "${{ contains(needs.*.result, 'failure') && false || true }}"
+          echo "${{ needs.release.result }}"
+          echo "${{ needs.test.result }}"
+
       - name: Notify User
         uses: https://${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/gitea-workflows-notification@main
         with:
